// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Evently.Modules.Attendance.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class MaterializedViews2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "attendees_checked_in",
                schema: "attendance",
                table: "event_statistics",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<List<string>>(
                name: "duplicate_check_in_tickets",
                schema: "attendance",
                table: "event_statistics",
                type: "text[]",
                nullable: false);

            migrationBuilder.AddColumn<List<string>>(
                name: "invalid_check_in_tickets",
                schema: "attendance",
                table: "event_statistics",
                type: "text[]",
                nullable: false);

            migrationBuilder.AddColumn<int>(
                name: "tickets_sold",
                schema: "attendance",
                table: "event_statistics",
                type: "integer",
                nullable: false,
                defaultValue: 0);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "attendees_checked_in",
                schema: "attendance",
                table: "event_statistics");

            migrationBuilder.DropColumn(
                name: "duplicate_check_in_tickets",
                schema: "attendance",
                table: "event_statistics");

            migrationBuilder.DropColumn(
                name: "invalid_check_in_tickets",
                schema: "attendance",
                table: "event_statistics");

            migrationBuilder.DropColumn(
                name: "tickets_sold",
                schema: "attendance",
                table: "event_statistics");
        }
    }
}
