<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Aspire -->
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.10.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.RabbitMQ" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.Keycloak" Version="13.5.3-preview.1.26425.3" />
    <!-- Static code analysis -->
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.34.0.3385" />
    <!-- Common Domain -->
    <PackageVersion Include="Ulid" Version="1.4.1" />
    <!-- Common Application -->
    <PackageVersion Include="MediatR.Contracts" Version="2.0.1" />
    <PackageVersion Include="MassTransit.Abstractions" Version="8.5.10" />
    <!-- Common Application -->
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.5.3" />
    <!-- Common Infrastructure -->
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.5.3" />
    <PackageVersion Include="MassTransit" Version="8.5.10" />
    <PackageVersion Include="MassTransit.Redis" Version="8.5.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Quartz.Extensions.Hosting" Version="3.21.0" />
    <PackageVersion Include="Scrutor" Version="7.0.0" />
    <!-- Modules -->
    <!-- Application -->
    <PackageVersion Include="MediatR" Version="14.2.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <!-- Infrastructure -->
    <PackageVersion Include="Aspire.Npgsql" Version="13.5.3" />
    <PackageVersion Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <!-- Evently.Api -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.3" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />
    <!-- Tests -->
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="FluentAssertions" Version="6.12.2" />
    <PackageVersion Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageVersion Include="Testcontainers.Keycloak" Version="4.15.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.15.0" />
    <PackageVersion Include="Testcontainers.Redis" Version="4.15.0" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
  </ItemGroup>
</Project>