<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Static code analysis -->
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.29.0.143774" />
    <!-- Common Domain -->
    <PackageVersion Include="Ulid" Version="1.4.1" />
    <!-- Common Application -->
    <PackageVersion Include="MediatR.Contracts" Version="2.0.1" />
    <PackageVersion Include="MassTransit.Abstractions" Version="9.1.2" />
    <!-- Common Application -->
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.4.6" />
    <!-- Common Infrastructure -->
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.4.6" />
    <PackageVersion Include="MassTransit" Version="9.1.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <!-- Modules -->
    <!-- Events -->
    <!-- Events Application -->
    <PackageVersion Include="MediatR" Version="14.2.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <!-- Events Infrastructure -->
    <PackageVersion Include="Aspire.Npgsql" Version="13.4.6" />
    <PackageVersion Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <!-- Evently.Api -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.16" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <!-- ArchitectureTests -->
    <!-- Aspire -->
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.8.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.8.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.17.0" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageVersion Include="Aspire.Hosting.RabbitMQ" Version="13.4.6" />
    <PackageVersion Include="Aspire.Hosting.Keycloak" Version="13.4.6-preview.1.26319.6" />
  </ItemGroup>
</Project>