<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\Modules\Users\Evently.Modules.Users.IntegrationEvents\Evently.Modules.Users.IntegrationEvents.csproj" />
        <ProjectReference Include="..\Evently.Common.Application\Evently.Common.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql" />
        <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
        <PackageReference Include="CommunityToolkit.Aspire.MassTransit.RabbitMQ" />
        <PackageReference Include="EFCore.NamingConventions"/>
        <PackageReference Include="MassTransit.Redis" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
        <PackageReference Include="AspNetCore.HealthChecks.Redis" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="Quartz.Extensions.Hosting" />
        <PackageReference Include="Scrutor" />
    </ItemGroup>

</Project>
