<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Evently.Common.Application\Evently.Common.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    </ItemGroup>

</Project>
